### ISSUE TITLE
Node.js integration enabled and attempted to load remote content. This exposes users of this app to severe security risks

### ISSUE THREAD

**Issue by D3m0nKingx** [stratisproject/StratisCore#108]
![image](https://user-images.githubusercontent.com/18432686/47219597-43ffa400-d37d-11e8-8b45-bf86762806ae.png)

File/code:
/home/demon/coins/StratisCore/StratisCore.UI/node_modules/electron/dist/resources/electron.asar/renderer/init.js:162

**Comment by dev0tion** [comment]
Hey @bokobza this is not a bug but expected behavior.
In the production environment the index file gets loaded from dist/index.html, which is seen as loading external content.

**Comment by bokobza** [comment]
Anything we can do here @dev0tion ?

**Comment by dev0tion** [comment]
No it's expected behaviour for how we launch the code now @bokobza.
You can close if you want.

**Comment by bokobza** [comment]
Closing.
