### ISSUE TITLE
Improve how we display error message

### ISSUE THREAD

**Issue by bep42** [stratisproject/StratisCore#146]
When we use a modal dialog box and the action went wrong, it displays another modal dialog over the first one. This is not useful and user friendly by the way.
I suggest to only display like other modal dialog with forms an error message in red under the field. 

<img width="1262" alt="capture d ecran 2018-11-26 a 09 25 51" src="https://user-images.githubusercontent.com/6614362/49001749-ec174280-f15d-11e8-965a-5522c3dafbfe.png">

/cc @dev0tion @bokobza

**Comment by bep42** [comment]
<img width="1262" alt="capture d ecran 2018-11-26 a 09 32 31" src="https://user-images.githubusercontent.com/6614362/49001885-3ac4dc80-f15e-11e8-9c1a-7b272ad4b910.png">

Please follow this example. The code is ready but we need to use it directly, not after the second modal dialog closed.

**Comment by bep42** [comment]
@dev0tion is this ok for this issue ? :)

**Comment by dev0tion** [comment]
Done throughout the entire wallet
