### ISSUE TITLE
Dump Private Keys

### ISSUE THREAD

**Issue by clintnetwork** [stratisproject/StratisCore#163]
Hello,

I would like to export my private keys, does there has a solution with the full node or other ?

Thank you

**Comment by dev0tion** [comment]
Hey @clintnetwork,

Have a look here to see how HD works: https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki

We won't support anything like this anytime soon I think.

**Comment by clintnetwork** [comment]
Hello @dev0tion,

Someone explained to me the same thing shortly after I created this issue.

For the wallet you're right, but I think that in the cryptography world, the membership of its private keys is important, maybe you could do a tutorial to extract them with the mnemonic using this by example: https: // iancoleman.io/bip39/ or by adding the features in the full node :)

I really believe that we must have the opportunity to obtain our private key for any address.

Thank you, it was my opinion

**Comment by dev0tion** [comment]
I agree that it would be a nice to have tool, maybe we can make it a community bounty project.

**Comment by clintnetwork** [comment]
Yep good idea
