### ISSUE TITLE
RAM leak Ubuntu 16.04

### ISSUE THREAD

**Issue by ElvisPresly** [stratisproject/StratisCore#174]
3GB Ram
![screen shot 2018-12-17 at 20 26 46 pm](https://user-images.githubusercontent.com/18265958/50209504-f86d7480-0384-11e9-96a4-518011094eaf.png)

**Comment by dev0tion** [comment]
We're currently working on improving the memory usage.
I'm closing this because it belongs in http://github.com/stratisproject/stratisbitcoinfullnode
