### ISSUE TITLE
scanning QR code add "stratis:" to prefix

### ISSUE THREAD

**Issue by trunghieud** [stratisproject/StratisCore#218]
When scanning QR code from Stratis Core 1.1.0, it added "stratis:" to prefix:
 
![QR_Code](https://user-images.githubusercontent.com/29716420/54956875-5bcfeb00-4f0e-11e9-8191-b2f5e5af1c5a.jpeg)

**Comment by mrtpain** [comment]
This looks intentional but I don't know it's purpose. 

```
const networkName = this.globalService.getSidechainEnabled() ? 'cirrus' : 'stratis';
this.qrString = `${networkName}:${response}`;
```

**Comment by dev0tion** [comment]
This is indeed intentional and the first step of implementing a Stratis URI scheme.
More info: https://www.webfx.com/blog/web-design/qr-codes-uri-schemes/

Closing the issue.
