### ISSUE TITLE
Pop up asking users to confirm they understand the seed words/recovery

### ISSUE THREAD

**Issue by acetmesis** [stratisproject/StratisCore#220]
Suggestion from the Discord: a pop up asking the wallet creator to confirm that they have stored the seed words and understand their role in the recovery of the wallet - click to confirm and move on, click to go back to the seed words.

**Comment by acetmesis** [comment]
> Suggestion from the Discord: a pop up asking the wallet creator to confirm that they have stored the seed words and understand their role in the recovery of the wallet - click to confirm and move on, click to go back to the seed words.

**Comment by acetmesis** [comment]
May be unnecessary given that it asks you to input some of the words anyway?

**Comment by dev0tion** [comment]
Yes that was our intention with confirming the seed words, however a confirmation box might be helpful as well.
I'm leaving this issue open and I will discuss on adding it. Thanks.
