### ISSUE TITLE
button -> Open folder

### ISSUE THREAD

**Issue by martinhoule** [stratisproject/StratisCore#221]
Should be a good idea to add a open folder for the %appdata%, something like this
![image](https://user-images.githubusercontent.com/16035523/57016293-5d649100-6be7-11e9-851c-257c7d1b66e6.png)

**Comment by dev0tion** [comment]
I agree. Will create a task for this and it will make one of the upcoming releases.
Thanks for the suggestion!

**Comment by dev0tion** [comment]
Added in #242
