### ISSUE TITLE
Specify datadir in Stratis Core?

### ISSUE THREAD

**Issue by realuser** [stratisproject/StratisCore#239]
Last time I used Stratis it was the QT wallet and now I understand there is Stratis Core.  With the QT wallet I would run it using the `-datadir` option so I could specify the storage location of the blockchain.  Is there an equivalent option for Stratis Core?

**Comment by TjadenFroyda** [comment]
Yes - added in #219. Right click the shortcut and add the option to the command outside of the parenthesis. You can add other SFN options this way too.

**Comment by realuser** [comment]
I'm not sure what you mean by parenthesis as I don't see them somewhere in the shortcut. I right clicked the Stratis Core shortcut that the installer puts on the Windows desktop and went to properties. I changed the `Target` from:
`"C:\Program Files\Stratis Core\Stratis Core.exe"`
to:
`"C:\Program Files\Stratis Core\Stratis Core.exe" -datadir=D:\crypto\stratisdata`

I opened Stratis Core via this shortcut but nothing is being put in the folder I specified.  When I click on "Advanced" in the wallet and look at about page the "Wallet data directory" shows:
`C:\Users\Username\AppData\Roaming\StratisNode\stratis\StratisMain`

Am I doing something wrong or is this not working?

**Comment by TjadenFroyda** [comment]
Sorry, meant quotes. You have it right. 

Have you built from latest master or are you using the last release? This came after the last release.

**Comment by realuser** [comment]
I'm using the latest release.  Any rough idea of when this change will make it into a release? Month, 6 months, year?

**Comment by TjadenFroyda** [comment]
No idea about team's release schedule. Soon maybe?

**Comment by dev0tion** [comment]
A new version of Core can (and probably will) be released together with the Sidechains release (1 July).
