### ISSUE TITLE
Let user choose it's own Full Node

### ISSUE THREAD

**Issue by pablos91** [stratisproject/StratisCore#253]
Hi guys, I was wondering if in the next version you'll let to choose your own full node working in the same network?

At this moment I had to fork your project and make own build pointing at my already functioning full node.

Are you planning to do such thing in near future?

Thanks for info!

**Comment by pablos91** [comment]
Ok i think it has been poorly documented that you can run Stratis.Core with a parameter `--daemonip` anyways it just waits for the node to initialize ? Even though my node is fully synchronized?

Atm:

```
======Node stats====== 07/09/2019 17:48:30
Headers.Height:      1379238  Headers.Hash:     6780b33b6fa2b875e06f596396ff0d6b9f2e2a8495816d9f149b8fd580993f91
Consensus.Height:    1379238  Consensus.Hash:   6780b33b6fa2b875e06f596396ff0d6b9f2e2a8495816d9f149b8fd580993f91
BlockStore.Height:   1379238  BlockStore.Hash:  6780b33b6fa2b875e06f596396ff0d6b9f2e2a8495816d9f149b8fd580993f91
Wallet.Height:       1379238  Wallet.Hash:      6780b33b6fa2b875e06f596396ff0d6b9f2e2a8495816d9f149b8fd580993f91
```

Here's the screenshot when running with  `--daemonip=192.xxx.xxx.xxx`  entered (ip masked for purpose)

![image](https://user-images.githubusercontent.com/1850835/60911207-f3213a00-a282-11e9-8e99-62d0d7030395.png)


Thanks

**Comment by pablos91** [comment]
Ammm, okay guys we cool I think it's because I'm running 3.0.3.0 instead of 3.0.4.0 node. Gonna update when it builds.

**Comment by pablos91** [comment]
Ok guys, everything is fine - that's the exact functionality i was looking for.

Please add proper documentation for commandline arguments and we are good.

Thanks!

**Comment by dev0tion** [comment]
Hey @pablos91, good that you've solved your own issue :). We'll work on adding the appropriate documentation.
