### ISSUE TITLE
[Suggestion][Discussion] Add Federation Addresses to Wallet

### ISSUE THREAD

**Issue by mrtpain** [stratisproject/StratisCore#261]
Several people have brought this up and had to inconveniently look up these addresses several times just to send tokens back and forth. 

Lets talk about pros and cons to adding this into Stratis Core as maybe a dropdown or quick select option as these are both maintained by Stratis. 

Sidechain Federation Address: `cnYBwudqzHBtGVELyQNUGzviKV4Ym3yiEo`
Mainchain Federation Address: `sg3WNvfWFxLJXXPYsvhGDdzpc9bT4uRQsN`

UI wise, input field for this should stay so users can easily send funds to new chains but should have easy button for Stratis and Cirrus Mainnet.

The only push back I received on this was that if a user has an unofficial tampered version of the app, users may be mislead and use the wrong federation address. This IMO is not a valid enough reason, the entire project is open source, if a user has an official version of Stratis Core there is a lot more things to worry about that could have been done to the full node or Stratis Core itself aside from tampering with these hard coded addresses. 

Thoughts? I'd really like to see this improvement made, nobody should have to Google around to find these addresses when working within the wallet. 

At the very least, let's get these addresses added to the README.

**Comment by dev0tion** [comment]
Agreed, as long as the user has the option to manually input addresses I'm more than ok with this change.

**Comment by mrtpain** [comment]
Awesome! I'll take care of the PR over the next couple days.

**Comment by dev0tion** [comment]
Ok, I will have a look at Core documentation to see what is outdated and what we can add (I.E. the federation addresses).

**Comment by dev0tion** [comment]
Added in 2.0.0.0
