### ISSUE TITLE
Cirrus and Core wallet display white screen (UI crash?) 

### ISSUE THREAD

**Issue by trunghieud** [stratisproject/StratisCore#263]
@dev0tion I faintly remember this was an issue with the UI? It has happen twice in the last week. I had to close and re-launched the application. Attached are some screenshots and logs.  
Core log show an error:
PeerConnectorAddNode.ConnectAsync                                               Loop           Faulted        
      * Fault Reason: Collection was modified; enumeration operation may not execute.

[CirrusMain_node.zip](https://github.com/stratisproject/StratisCore/files/3484765/CirrusMain_node.zip)
![Stratis_Cirrus_Core_WhiteScreen](https://user-images.githubusercontent.com/29716420/62754526-1592a880-ba25-11e9-9a70-fb8a50c2e038.JPG)
![TaskManager_CirrusCore_WhiteScreen](https://user-images.githubusercontent.com/29716420/62754527-1592a880-ba25-11e9-9ca3-6e93840b9d91.JPG)
![TaskManager_CirrusCore_WhiteScreen2](https://user-images.githubusercontent.com/29716420/62754528-162b3f00-ba25-11e9-92b9-5330cdcf625e.JPG)

**Comment by dev0tion** [comment]
Ok interesting, though the error is not relevant to the blank screen issue.
Is there a way you can always reproduce the blank screen?

**Comment by trunghieud** [comment]
I guess the error is a separate issue. I have not 100% reproduce the issue yet, but I do have a theory/data on how it is occurring. Here is my configuration:

PC-1: Masternode on HDMI 1
PC-2: Core 1.2.0 and Cirrus 1.2.1 on HDMI 2

Some days, I unplugged HDMI on PC-1 and plugged it into my mac to do some research for the rest of the day. In the morning, I plugged HDMI back to PC-1. When I come home after work, I check HDMI 1 and HDM 2. HDMI 1 still show MN PC, but HDMI 2 shows a blank screen. When I close the application and relaunch it, the node are not sync and the details show I received a staking reward. 

So it seem this UI crash is related to no video signal and staking reward on the network.

**Comment by trunghieud** [comment]
So it happened multiple times yesterday. I didn’t even unplug any hdmi cable. It seems to be related to memory usage...... task manager shows memory usage over 90%. I clean up some tabs and application  to lower memory. It hasn’t happened since. Will monitor. 

Maybe you guys can reproduce by maxing out your memory usage.

**Comment by dev0tion** [comment]
Thanks will try that @trunghieud.
FYI: we actually found a bug with the error message you provided. A quick fix has been merged already and the extended fix is being reviewed right now, so thanks again for reporting the issue!
