### ISSUE TITLE
Include Commit Head in versioning

### ISSUE THREAD

**Issue by FyreDemonyte** [stratisproject/StratisCore#279]
This is more of a suggestion to follow the commit history easier when users need to troubleshoot issues.

Simply to have the application version to also specify the commit head which it was compiled from, in the same fashion the c++ version does.

For example, today a user clones the repository, compiles it, goes to the about dialogue of the UI, and will see:
![Screenshot from 2019-09-23 20-58-19](https://user-images.githubusercontent.com/18432686/65473242-ea351300-de44-11e9-82db-6025c4a66576.png)

But rather it should read: 
```bash
Wallet Version:        1.2.1-ae4cba
FullNode Version:      3.0.4.0-4d09bd
```
This will help diagnosing issues further by knowing exactly which code the user is working with. since for example at the moment there have been other commits since it's been bumped to version 1.2.1.

**Comment by dev0tion** [comment]
Added (for the wallet version) in 2.0.0.0
