### ISSUE TITLE
Discussion - Increase Default Gas Limit

### ISSUE THREAD

**Issue by mrtpain** [stratisproject/StratisCore#307]
In my testing of the Airdrop contract, even the simplest calls required a bit more than 10_000 gas. Most calls were around 10_500. New contracts or expensive calls reached up to about 14_000. 

Maybe a new default around 11_000 would be a good start. 
15_000 would be a safe bet to allow tokens, contracts, etc. to not run out of gas.

**Comment by dev0tion** [comment]
@rowandh @codingupastorm

**Comment by rowandh** [comment]
Good idea, 10k is the base fee and won't allow you to get anything else done in a contract so we could definitely bump this up. Something around 14-15k I feel would be the sweet spot.

**Comment by dev0tion** [comment]
Hey @rowandh any progress on this? Does the issue need to remain open? Thanks!

**Comment by mrtpain** [comment]
@dev0tion I think this is a UI fix, the default limit shown in current wallet versions is 10_000.

**Comment by dev0tion** [comment]
I know @mrtpain, I'm just wondering if they have discussed increasing it and if yes, to what value.

**Comment by rowandh** [comment]
Discussed with @codingupastorm and we agree that 15k is a sensible limit.
