### ISSUE TITLE
Unable To Connect to Stratis Node

### ISSUE THREAD

**Issue by moneyafric** [stratisproject/StratisCore#335]
I have been trying to load the wallet to create stratis wallet account but it failed. Look into this now.
![Unable To Connect to Stratis Node](https://user-images.githubusercontent.com/35640233/68709514-1db73280-0596-11ea-8c8f-57b6260498ed.png)

**Comment by dev0tion** [comment]
Were you able to resolve this by now?
If you need support, the quickest way to reach us one-to-one is on Discord.
You can join here: https://discord.gg/jQUgUyF and find us in the #support channel.
Ping me there (@dev0tion)

Closing this issue as this is likely to be resolved after talking to us.
