### ISSUE TITLE
Can't connect to anything

### ISSUE THREAD

**Issue by AGowans** [stratisproject/StratisCore#344]
I updated to 1.31, and it loads for 10 minutes and comes back with "can't connect to a node".

I can't even get the wallet open to do anything, and the localhost rejects any connection attempts via browser since the wallet isn't actually loading.

**Comment by StratisUser123** [comment]
I have the same issue.... did you ever get this resolved ?

**Comment by AGowans** [comment]
No. I have tried on a few machines, Linux and Windows.

Can't get anything to connect, and have not been able to get a response from the Stratis project. See if pinging them here helps...
 
@sondreb @YakupIpek @Daegalus

**Comment by FyreDemonyte** [comment]
I'm a linux user, updated to v1.3.1. Compiled and started the node with `npm run package:linux` then entering the **StratisCore.UI/app-builds/linux-unpacked** directory and starting core with `./stratis-core` 

This resulted in one connection so far with:

```C#
      OUT Peer:[::ffff:217.7.52.43]:16178,            (r/s/c):412193/412193/0               R/S MB: 4.78/0.11               agent:StratisNode:3.0.5 (70012)
```

**Comment by AGowans** [comment]
I still get the same thing.

Cloned repo, built, ran from directory as instructed .

Shows the loading screen for 4-5 minutes, then I get "Failed to load, can not connect to a stratis node"

**Comment by FyreDemonyte** [comment]
What are you seeing in the terminal ?

**Comment by dev0tion** [comment]
@AGowans have you tried shutting down Core, removing peers.json in ~/.stratisnode/Stratis/StratisMain and starting Core again?

**Comment by dev0tion** [comment]
Seeders updated in Core 2.0.0.0, should no longer be an issue. Closing.
