### ISSUE TITLE
Orphans in transaction history (Core 2.0.0 RC2)

### ISSUE THREAD

**Issue by programmereddie** [stratisproject/StratisCore#441]
Staking in Stratis Core 2.0.0 - RC2 shows orphans as staked in the transaction history.

Restarting core filters the orphans out, but new stakes include orphans again in the transaction history of core.

**Comment by dev0tion** [comment]
Hi @programmereddie, this issue should be fixed with the official v2.0.0.0 release.
Please reopen the issue if you still encounter the problem. Thanks.
