### ISSUE TITLE
Scrolling through transaction/staking history bugs (Core 2.0.0-RC2)

### ISSUE THREAD

**Issue by programmereddie** [stratisproject/StratisCore#442]
1. In a small window scrolling through staking history stutters a little (in full screen it works smooth).

2. In the latest transaction pane (account window of core) opening and closing a transaction detail and then scrolling through the transaction history will automatically open the transaction details again that I closed.

**Comment by dev0tion** [comment]
Hi @programmereddie, this was fixed/changed in the official v2.0.0.0 release.
