### ISSUE TITLE
UI not updating staking rewards 

### ISSUE THREAD

**Issue by trunghieud** [stratisproject/StratisCore#444]
There’s a very odd issue going on here but I haven’t been able to identify what happened. This has happened twice so far:

The first time it was about 2 weeks ago or so. I had core RC2 for 1-2 weeks and did not see any rewards at all! I check the staking menu and account. No updates whatsoever. I selected different menu and no change. I ping @dev0tion and he told me to restart. After I restarted, all the staking rewards appear....

The second time was today. Same exact issue. It was three days since I had a reward so I restarted my wallet and the staking rewards appear. 

This seem to be some UI bug.

**Comment by dev0tion** [comment]
Hi @trunghieud, I'm aware of the issue and I'm testing a fix locally.
When you have this issue next time, can you please try scrolling up and see if the transactions appear?

Cheers.

**Comment by dev0tion** [comment]
Hi @trunghieud, I was not able to reproduce this after the fix, so it should be a problem of the past with the official v2.0.0.0 binaries.
Please reopen the issue if you still encounter the problem.
