### ISSUE TITLE
linux wallet unable to connect to stratis node

### ISSUE THREAD

**Issue by ialkeilani** [stratisproject/StratisCore#446]
after downloading, installing the stratis core deb package then running it, i'm faced with error message:
"Loading Failed - Unable to connect to Stratis Node."
"If you continue to receive this message after restarting, please have a look at the support section here"

the link to the support section, does not offer any support really.  Would appreciate any helpful debugging tips

**Comment by dev0tion** [comment]
Hi,

Which version of Linux are you running?

I assume you're trying to run Stratis Core v1.3.1? 
Please try v2.0.0.0 RC2: https://github.com/stratisproject/StratisCore/releases/tag/2.0.0.0-RC2

**Comment by ialkeilani** [comment]
Thanks for looking into this.


I am running ubuntu 20.04.1 LTS
And correct i was running v1.3.1

i unistalled v1.3.1 and installed v2.0.0.0 RC2.  This one crashes as soon as I launch it giving me this error message:
_"The application Stratis Core has closed unexpectedly.
send problem report to the developers?
ExecutablePath
    /opt/Stratis Core/resourses/daemon/Stratis.StratisD
Package
    stratis-core 2.0.0-24131 [origin: unknown]
ProblemType
    Crash
Title
    Stratis.StratisD crashed with SIGABRT in InitializeOpenSSLShim()
..."_

Crash report is rather lengthy.  ubuntu doesn't let me copy it but I typed what seemed relavent to help get this root-caused.  Let me know if there's something else I can get you?

**Comment by dev0tion** [comment]
I will have to have a look myself.
I'll get a 20.04 VM in the weekend and test it out, will keep you posted.

**Comment by enigma158an201** [comment]
hi,
same issue with both stratis-core v1.3.1 and v2 on ubuntu 20.04.1

![Capture d’écran de 2020-09-25 21-44-28](https://user-images.githubusercontent.com/35665243/94309406-52e32e00-ff78-11ea-9e52-5f7c59c08394.png)

would you advice to run in linux debian or other linux distro?

**Comment by dev0tion** [comment]
Hi guys, we have just released v2.0.0.0 officially.
I was able to install the .deb on 20.04 and run it. 
Can you please try with the official binary?
https://github.com/stratisproject/StratisCore/releases/tag/2.0.0.0

Cheers

**Comment by enigma158an201** [comment]
hi,
just updated to new official v2
seems there is no crash issue, but i still have to connect my account (login failed)

**Comment by dev0tion** [comment]
Connect to your account? Login failed? I'm sorry what do you mean?

**Comment by enigma158an201** [comment]
it's ok, since i updated stratis full node to last version...

**Comment by dev0tion** [comment]
@ialkeilani please confirm as well, thanks.

**Comment by ialkeilani** [comment]
official v2.0.0.0 still won't work

debian package: I get a crash notification, but stratis still continues to run and eventually gives "Loading Failed - Unable to connect to Stratis Node."
![Screenshot from 2020-09-25 20-26-37](https://user-images.githubusercontent.com/6824858/94325870-9fc20700-ff6e-11ea-9311-81495b46bd84.png)

![Screenshot from 2020-09-25 20-35-00](https://user-images.githubusercontent.com/6824858/94325878-a5b7e800-ff6e-11ea-8dc2-1009c34fa593.png)

Standalone: no crash, just the "Loading Failed" message same as above

p.s i'm running stratis core on windows from a virtual machanice on same host with no issues

**Comment by dev0tion** [comment]
Can you open terminal and launch stratis-core in there?
You should just be able to type stratis-core and it will launch. The terminal should give you some more information on why the process fails.

**Comment by ialkeilani** [comment]
That's what I get on terminal:
![Screenshot from 2020-09-26 21-28-00](https://user-images.githubusercontent.com/6824858/94353441-41188e00-003f-11eb-8660-8d181b0d7a79.png)

**Comment by dev0tion** [comment]
Thanks for the feedback @ialkeilani 
Did you alter the version of glibc by any chance?
If not, can you try updating your system and try to run again.
```
sudo apt update
sudo apt upgrade
sudo apt dist-upgrade
sudo apt autoremove
sudo apt autoclean
```
These can be used to update your OS to the latest and greatest. 
Please check the packages that would be updated to see if your other applications can support the newer versions.

**Comment by dev0tion** [comment]
I have just merged a change that could potentially solve this issue: https://github.com/stratisproject/StratisCore/tree/release/2.0.0.0
You can either build from source or wait until a new version has been released that includes this change.

If you trust the executable that I build, you can find it [https://stratisplatform-my.sharepoint.com/:u:/p/pieterjan_vanhoof/EQU-6iPnYtJHglwW-VPh9ngBw09uh6VxnOg12DOlCt8uCA?e=eB9ykR](here)
Though I would not recommend downloading any executables other than the ones on official sources.

**Comment by ialkeilani** [comment]
thanks for all the help attempts
no i did not alter the glibc.  I'm not sure what the exact package name, but the closest I have on my machine is called "libc".  Its info below.

So i tried deleting the conf directory, that didn't do it.  Then I also tried the system update also no luck.  I will give your one-off build a shot after spinning off a new VM and let you know.  thanks a lot for looking into this


Package: libc6                           
Version: 2.31-0ubuntu9.1
State: installed
Automatically installed: yes
Multi-Arch: same
Priority: required
Section: libs
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Uncompressed Size: 13.6 M
Depends: libgcc-s1, libcrypt1 (>= 1:4.4.10-10ubuntu4)
Recommends: libidn2-0 (>= 2.0.5~)
Suggests: glibc-doc, debconf | debconf-2.0, locales
Conflicts: openrc (< 0.27-2~)
Breaks: hurd (< 1:0.9.git20170910-1), iraf-fitsutil (< 2018.07.06-4), libtirpc1 (< 0.2.3), locales (< 2.31), locales:i386 (< 2.31), locales-all (< 2.31),
        locales-all:i386 (< 2.31), nocache (< 1.1-1~), nscd (< 2.31), nscd:i386 (< 2.31), r-cran-later (< 0.7.5+dfsg-2), wcc (< 0.0.2+dfsg-3), libc6:i386 (!=
        2.31-0ubuntu9.1)
Replaces: libc6-amd64, libc6-amd64:i386, libc6-amd64:x32, libc6-amd64:x32-i386-cross, libc6-amd64:i386-x32-cross, libc6:i386 (< 2.31-0ubuntu9.1)
Description: GNU C Library: Shared libraries
 Contains the standard libraries that are used by nearly all programs on the system. This package includes shared versions of the standard C library and the
 standard math library, as well as many others.
Homepage: https://www.gnu.org/software/libc/libc.html

**Comment by ialkeilani** [comment]
Just finished testing it on a fresh ubuntu LTS 20.04 VM.  When the app is launched, the one-off produces no errors on command line, but the app eventually gives the same "Loading Failed - Unable to connect to Stratis Node."

**Comment by dev0tion** [comment]
Is there anything useful in the node.txt file in ~/.stratisnode/Stratis/StratisMain/logs? 
You no longer get the crash report, right?

**Comment by ialkeilani** [comment]
correct no more crashing.
actually i have no logs file in ~/.stratisnode/Stratis/StratisMain/
Similarly, I got no json file.  The only thing in ~/.stratisnode/Stratis/StratisMain is the stratis.conf file.  So i tried moving it outside and re-starting, same "Loading Failed" error

Do you have this working for you on 20.04?  I have a clean fresh install and it's not working, so I'm thinking no body can currently run the wallet on 20.04??

**Comment by dev0tion** [comment]
I have this working on 20.04 indeed, but it was an existing VM where I tested some development related stuff on.
Do you have a version of Dotnet Core installed by any chance?

I'll get a 20.04 fresh VM running tonight and test.

**Comment by ialkeilani** [comment]
no i don't have .net core installed

**Comment by dev0tion** [comment]
Hi all, 

I was able to have a decent look into this today. Looks like .NET Core 2.1 does not support the default version of libssl on Ubuntu 20.04. 
This will no longer be an issue in the new STRAX wallet, as that is using .NET Core 3.1 which does support that version of libssl.

Anyway, workaround is to open terminal and execute these commands:
`wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
dpkg -i ./libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb`

**Comment by ialkeilani** [comment]
thanks really appreciate your help on this.  Unless you would like me to try out the workaround, I will wait till the STRAX wallet is released then

**Comment by dev0tion** [comment]
Please not that Stratis Core and STRAX are two different blockchains.
You can only use Stratis Core for STRAT and the swap.
STRAX Wallet will be the client used after the swap.

More information can be found here:
https://www.stratisplatform.com/2020/09/25/introducing-strax/
https://www.stratisplatform.com/2020/10/15/strax-token-swap/
https://www.stratisplatform.com/2020/10/19/token-swap-faq/

**Comment by ialkeilani** [comment]
I tired version 2.2.1 and I can confirm the workaround of using older version of libssl works!

Thank you!

**Comment by ialkeilani** [comment]
I tired version 2.2.1 and I can confirm the workaround of using older version of libssl works!

Thank you!
