### ISSUE TITLE
Wallet is not notified if the transaction cannot be fulfilled

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisCore#45]
When attempting to spend not matured/recently staked coins the transaction is not accepted to the memory pool and the wallet is not notified of this.

As a result the wallet shows that the transaction has been sent and is pending confirmation wheres in fact the transaction was never shared across the network.

**Comment by bokobza** [comment]
Fixed since commit https://github.com/stratisproject/StratisBitcoinFullNode/commit/57eca2c3.
