### ISSUE TITLE
token swap is not working

### ISSUE THREAD

**Issue by weetie** [stratisproject/StratisCore#460]
Stratis Core 2.1.1

**Something went wrong**
 Not enough funds to cover the target with missing amount
0.00000110

**Comment by weetie** [comment]
if it is really impossible to calculate fees you should maybe let the people edit the amount of tokens to swap

**Comment by weetie** [comment]
and it is not great to be forced to swap if this is not working

**Comment by dev0tion** [comment]
Hi, please update to v2.2.1 where this issue has been resolved: https://github.com/stratisproject/StratisCore/releases/tag/2.2.1.0

**Comment by weetie** [comment]
hello dev0tion, I tried Version 2.2.0 before 2.1.1 and this did not work either, due to some "bitcoin" error, but now I could burn my stratis token.

Thank you very much
