### ISSUE TITLE
STRATIS CORE 2.2.1 - error trying to connect to the server

### ISSUE THREAD

**Issue by wcanarro** [stratisproject/StratisCore#463]
I have just installed the 64 bit version of the stratis core 2.2.1 on windows 10 to perform the strax token swap but when I run the application I keep receiving the error "Unable to connect to Stratis Node"

Best,
Danilo

**Comment by dev0tion** [comment]
Hi, please check %appdata%/StratisNode/Stratis/StratisMain/Logs/node.txt to see if there are any errors/exception. They would normally be located at the bottom of the file.

**Comment by wcanarro** [comment]
Hi, sorry I didnt find the path "%appdata%/StratisNode/Stratis/StratisMain/Logs/node.txt"....maybe I should install more application than just the stratis Core.

**Comment by FyreDemonyte** [comment]
@wcanarro try finding the exact directory:

```bash
 C:\Users\[username]\AppData\StratisNode\StratisMain\Logs\node.txt
```

username = your username as you log in with into windows.

Also you could do a search a for *node.txt* in the search bar of windows explorer

**Comment by wcanarro** [comment]
Found!

[node.txt](https://github.com/stratisproject/StratisCore/files/5480825/node.txt)

**Comment by dev0tion** [comment]
Hi, looks like something went wrong with your database. Please do the following:
- Close Core
- Go to  C:\Users\[username]\AppData\StratisNode\StratisMain\
- Remove everything except the "wallets" folder and [your walletname].wallet.json. The second file might not be there.
- Start Core again

That should get you going again.

**Comment by wcanarro** [comment]
this is actually the path C:\Users\user\AppData\Roaming\StratisNode\stratis\StratisMain and I don't have the wallets folder neither the .json file.

**Comment by dev0tion** [comment]
Ok, that's fine, then you can proceed to remove everything.

**Comment by wcanarro** [comment]
ok, now I have the wallets folder, I think is all ok. Thank you for your support.

**Comment by dev0tion** [comment]
Ok, if you have any further questions you are welcome to join our Discord and ask them in our #support channel:
https://discord.com/invite/9tDyfZs
