### ISSUE TITLE
2.2.1 not possible to install

### ISSUE THREAD

**Issue by csh2000** [stratisproject/StratisCore#465]
Hello, W10 Home, x64.

Get this message when trying to install Stratis Core 2.2.1.

Downloaded from web page and github, both.

![Captura](https://user-images.githubusercontent.com/32745411/98436158-6e923600-20d9-11eb-8a21-47301c89b1c9.JPG)

Thanks.

**Comment by dev0tion** [comment]
Hi, could you try uninstalling the previous version first?

**Comment by csh2000** [comment]
Hello, uninstalled previous version, but I am having the same problem

In fact, I was only capable of reinstall 1.4.0, as 2.0.0 and above reproduce same message.

For information, I am having same error when updating today Ark 2.9.4... something to do with a Windows update??

Thanks!

**Comment by dev0tion** [comment]
It could have... Have you tried again after restarting your computer?

**Comment by csh2000** [comment]
Yes, same message.

**Comment by maartenn** [comment]
perhaps using a vm might help here?

**Comment by csh2000** [comment]
Finally run 2.2.1 on a fresh W10, works fine there.

I found other user with same problem and solution on Discord.

Thanks!

**Comment by dev0tion** [comment]
Considering "Ark 2.9.4" had the same issue, I'm thinking it's a bug in electron-builder, STRAX will be updated to the latest dependencies so should no longer be an issue there.
