### ISSUE TITLE
STRAX

### ISSUE THREAD

**Issue by wcanarro** [stratisproject/StratisCore#467]
HI, is the new strax mainnet live? Opening the wallet I don't see the tokens and actually the wallet doesn't have connections. 

best,
Danilo

**Comment by dev0tion** [comment]
It is yes, have you updated the STRAX Wallet to v1.0.0.0?
https://github.com/stratisproject/StraxUI/releases/tag/1.0.0.0

**Comment by wcanarro** [comment]
yes thank you I see the coins now.
