### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by neyxs** [stratisproject/StratisCore#476]
Hi,

I know many people already wrote about this issue on many topics but the solutions i founded appear to not work.

I sended stratis coins from "stratis-qt"  to "stratis-core", il worked but nothing appears now in stratis-core, no connection.

- I put manually the 3.0.8 nodes IP's.
- i downloaded the "Data Directory Archive" from another topic and pasted the content into the "StratisMain" folder, now it shows "up to date with X blocks" but 0 connection.
- I installed Stratis-Core & Stratis-qt on a virtual machine (windows 7 x86 without firewall and anti-virus). This one helped me to get Stratis-qt synced, on the regular machine he didn't sync. 
- Stratis-Core version : 2.2.1

Thanks.

**Comment by dev0tion** [comment]
Hi, I suppose you are trying to do the swap?
In that case the data directory sync you to the cut off point, which is all you need. 

You need to do the swap method on the wallet your funds were at on 12 November 9 AM GMT.
https://www.stratisplatform.com/2020/11/17/strax-token-swap-process/
The in wallet swap no longer works

**Comment by neyxs** [comment]
Thanks for the reply.

I did the "StratisX/QT Recovery Process" manipulation as my coins were on this wallet before the 12 November.
I have had a complete .csv file and did the swap, however 24 hours laters i don't still have them on my StraX Wallet (no connection/sync problem with this wallet by the way).

Edit: Finally i got them ! Thanks.
