### ISSUE TITLE
Stratis.Core-v2.2.1-mac Not Synching

### ISSUE THREAD

**Issue by Zimbakin** [stratisproject/StratisCore#483]
Core v2.2.1-mac is not synching. Tried quitting and deleting everything except the wallet folder, no success.
Tried adding additional nodes found online... nothing. 

My STRAT coins are stuck here. Want to transfer to STRAX, any suggestions?

**Comment by dev0tion** [comment]
Hi, you just have to get it synchronized to the cut-off point on November 12 then run through the swapping method.
You can download a data directory that gets you synced to 12 November. Have a look at the guide on page 11 step 6:
https://www.stratisplatform.com/wp-content/uploads/2020/11/STRAX-Token-Swap-Manual-Token-Swap-Windows.pdf

If you have any further questions I would recommend you to join our Discord and ask your questions in the #support channel.
https://discordapp.com/invite/9tDyfZs
