### ISSUE TITLE
Show Consensus.Height in the tooltip

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisCore#71]
![diff](https://user-images.githubusercontent.com/10259355/40579731-05f81c90-6137-11e8-9c98-e61e66090560.png)

In some cases knowing what is the latest block number is very useful. 
Can we also have this info when mouse is over the syncing icon?

**Comment by bep42** [comment]
That’s a fair point! We’ll see what we can do for the next release 👍🏼

**Comment by bokobza** [comment]
Closed with https://github.com/stratisproject/StratisCore/pull/111
