### ISSUE TITLE
Update the UI to be compatible with recent wallet API changes

### ISSUE THREAD

**Issue by sondreb** [stratisproject/StratisCore#79]
The full node have modification to the wallet API which requires full node UI to be modified.

Consider taking the PR submitted with this issue into the repo, at the point in time when the git submodule of fullnode daemon is updated.

Task is to add the new passphrase parameter to API call.

Feature suggestion: https://github.com/stratisproject/StratisBitcoinFullNode/issues/1677

**Comment by dev0tion** [comment]
I'll take this one @bokobza

**Comment by dev0tion** [comment]
Done in #140 and #142
