### ISSUE TITLE
Add Send to Sidechain modal

### ISSUE THREAD

**Issue by bokobza** [stratisproject/StratisCore#91]
This is the functionality allowing the user to send strats to a sidechain.
It's non-sidechain specific, the only requirement is that a cross-chain transaction is constructed, taking in an OP_RETURN containing the user's address on the sidechain.

Most of the design elements can be taken from https://github.com/stratisproject/StratisCore/pull/72

**Comment by bokobza** [comment]
The component can be found here:
https://github.com/stratisproject/StratisCore/tree/sidechains-ui/FullNode.UI/src/app/wallet/send

**Comment by dev0tion** [comment]
Done in #172
